name       : libsigc++
version    : 2.8.0
release    : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libsigc++/2.8/libsigc++-2.8.0.tar.xz : 774980d027c52947cb9ee4fac6ffe2ca60cc2f753068a89dfd281c83dbff9651
license    :
    - LGPL-2.1
summary    : The libsigc++ package implements a typesafe callback system for standard C++.
description: |
    The libsigc++ package implements a typesafe callback system for standard C++.
patterns   :
    - docs :
        - /usr/share/doc/libsigc++-2.0
        - /usr/share/devhelp
    - devel :
        - /usr/lib64/sigc++-2.0/include
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
