name        : libsigc++
version     : 2.4.1
release     : 5
source      :
    - http://ftp.gnome.org/pub/gnome/sources/libsigc++/2.4/libsigc++-2.4.1.tar.xz : 540443492a68e77e30db8d425f3c0b1299c825bf974d9bfc31ae7efafedc19ec
homepage    : http://www.gnome.org
license     :
    - GPLv2+
summary     : The libsigc++ package implements a typesafe callback system for standard C++.
description : |
    The libsigc++ package implements a typesafe callback system for standard C++.
patterns   :
    - docs:
        - /usr/share/doc/libsigc++-2.0
        - /usr/share/devhelp
    - devel:
        - /usr/lib64/sigc++-2.0/include
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
