name       : libsigc++
version    : 2.10.8
release    : 11
source     :
    - https://download.gnome.org/sources/libsigc++/2.10/libsigc++-2.10.8.tar.xz : 235a40bec7346c7b82b6a8caae0456353dc06e71f14bc414bcc858af1838719a
license    :
    - LGPL-2.1
summary    : The libsigc++ package implements a typesafe callback system for standard C++.
component  : desktop.gnome.core
description: |
    The libsigc++ package implements a typesafe callback system for standard C++.
patterns   :
    - docs :
        - /usr/share/doc/libsigc++-2.0
        - /usr/share/devhelp
    - devel :
        - /usr/lib64/sigc++-2.0/include
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
